export const RESTAURANTS_LOADING = 'RESTAURANTS_LOADING';
export const RESTAURANTS_FAILED = 'RESTAURANTS_FAILED';
export const ADD_RESTAURANTS = 'ADD_RESTAURANTS';
export const DISHES_LOADING = 'DISHES_LOADING';
export const DISHES_FAILED = 'DISHES_FAILED';
export const ADD_DISHES = 'ADD_DISHES';